export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  LEGALLY_ACCEPTED = 'LEGALLY_ACCEPTED',
  REJECTED = 'REJECTED',
  IN_DISPUTE = 'IN_DISPUTE',
}
